branches:
 only:
  - master

language: python

before_install:
  - echo "before_install"

install:
  - echo "install"

script:
  - echo "script"

after_success:
  - echo "success"

notifications:
  email: false
